---
- name: Install required bluetooth packages for james2
  ansible.builtin.package:
    name:
      - bluetooth
      - bluez
      - libbluetooth-dev
    state: present
  become: true
  become_user: root

- name: Enable and start bluetooth service
  ansible.builtin.service:
    name: bluetooth.service
    state: started
    enabled: true
  when: ansible_service_mgr == "systemd"
  become: true
  become_user: root

- name: Install python requirements for bluetooth
  ansible.builtin.pip:
    virtualenv_python: python3
    name:
      # revert to PyBluez when https://github.com/pybluez/pybluez/issues/416 is closed
      - git+https://github.com/pybluez/pybluez.git@master
    virtualenv: "{{ james2_install_dir }}/venv"
  become: true
  become_user: root
