---
- name: Install python requirements for caldav
  ansible.builtin.pip:
    requirements: "{{ james_on_rpi_install_dir }}/requirements-caldav-calendar.txt"
    virtualenv: "{{ james_on_rpi_install_dir }}/venv"
  become: true
  become_user: "{{ james_on_rpi_os_user }}"
