---

# the lirc package is ultimatively stupid and fails at installaion because the .dist file is not renamed to "non dist" if no other file is available ...
# so, the lirc package can not be installed by ansible without very big fuckery ... sry you had to come here and find this comment ... AGAIN
- name: remove old lirc JamesII packages
  ansible.builtin.package:
    name: lirc
    state: absent

- name: install required packages
  ansible.builtin.package:
    name: ir-keytable
    state: present

# ensure mounted boot
- name: mount boot
  ansible.posix.mount:
    path: /boot
    state: mounted
    src: /dev/mmcblk0p1
    fstype: vfat
  changed_when: false

# configuring RPI GPIO
- name: configure config.txt for lirc rx
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    regexp: '^dtoverlay=gpio-ir,gpio_pin='
    line: "dtoverlay=gpio-ir,gpio_pin={{ james2_lirc_rx_pin }}"
    insertafter: '^# Uncomment this to enable the lirc-rpi module'
  notify: reboot required
  ignore_errors: "{{ ansible_check_mode }}"

- name: configure config.txt for lirc tx
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    regexp: '^dtoverlay=gpio-ir-tx,gpio_pin='
    line: "dtoverlay=gpio-ir-tx,gpio_pin={{ james2_lirc_tx_pin }}"
    insertafter: '^dtoverlay=gpio-ir,gpio_pin'
  notify: reboot required
  ignore_errors: "{{ ansible_check_mode }}"

- name: put remote configs in place
  ansible.builtin.copy:
    src: "remotes/{{ item }}"
    dest: /etc/rc_keymaps/
    owner: root
    group: root
    mode: 0644
  loop: "{{ lircd_remotes }}"
  when: lircd_remotes is iterable

- name: configure remotes at boot
  ansible.builtin.cron:
    name: "Apply evdev keymap at reboot for {{ item }}"
    user: root
    special_time: reboot
    job: "/usr/bin/ir-keytable -v -s rc0 -c -w /etc/rc_keymaps/{{ item }} >/dev/null 2>&1"
  loop: "{{ lircd_remotes }}"
  when: lircd_remotes is iterable
  # TODO missing when lircd_remotes is defined or so
  # TODO rc0 or rc1 seems to change

- name: install python requirements for evdev
  ansible.builtin.pip:
    name:
      - evdev
    virtualenv: "{{ james2_install_dir }}/venv"
