---
- name: Install required JamesII packages
  ansible.builtin.package:
    name:
      - i2c-tools
    state: present

- name: "Adding existing user to group audio: {{ james_os_user }}"
  ansible.builtin.user:
    name: "{{ james_os_user }}"
    groups: i2c
    append: true

# ensure mounted boot
- name: Override config.txt location for Raspberry Pi OS version before bookworm
  ansible.builtin.set_fact:
    james_on_rpi_config_dir: /boot
  when: ansible_distribution_major_version | int < 12

- name: Mount boot
  ansible.posix.mount:
    path: "{{ james_on_rpi_config_dir }}"
    state: mounted
    src: /dev/mmcblk0p1
    fstype: vfat
  changed_when: false

- name: Configure config.txt for lirc rx
  ansible.builtin.lineinfile:
    path: "{{ james_on_rpi_config_dir }}/config.txt"
    regexp: "^dtparam=i2c_arm="
    line: "dtparam=i2c_arm=on"
    insertafter: "^# Uncomment some or all of these to enable the optional hardware interfaces"
  notify: Reboot required
  ignore_errors: "{{ ansible_check_mode }}"

- name: Ensure i2c_dev module is loaded
  ansible.builtin.lineinfile:
    path: /etc/modules
    regexp: "^i2c_dev"
    line: "i2c_dev"
  notify: Reboot required
  ignore_errors: "{{ ansible_check_mode }}"

- name: "Adding existing user to group audio: {{ james_os_user }}"
  ansible.builtin.user:
    name: "{{ james_os_user }}"
    groups: audio
    append: true

- name: Install python requirements for i2c
  ansible.builtin.pip:
    virtualenv_python: python3
    name:
      - smbus2
    virtualenv: "{{ james2_install_dir }}/venv"
