---
# Depricated, delete when evdev is working

# the lirc package is ultimatively stupid and fails at installaion because the .dist file is not renamed to "non dist" if no other file is available ...
# so, the lirc package can not be installed by ansible without very big fuckery ... sry you had to come here and find this comment ... AGAIN
- name: Install required JamesII packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present

# ensure mounted boot
- name: Override config.txt location for Raspberry Pi OS version before bookworm
  ansible.builtin.set_fact:
    james_on_rpi_config_dir: /boot
  when: ansible_distribution_major_version | int < 12

- name: Mount boot
  ansible.posix.mount:
    path: "{{ james_on_rpi_config_dir }}"
    state: mounted
    src: /dev/mmcblk0p1
    fstype: vfat
  changed_when: false

# configuring RPI GPIO
- name: Configure config.txt for lirc rx
  ansible.builtin.lineinfile:
    path: "{{ james_on_rpi_config_dir }}/config.txt"
    regexp: "^dtoverlay=gpio-ir,gpio_pin="
    line: "dtoverlay=gpio-ir,gpio_pin={{ james2_gpio_ir_rx_pin }}"
    insertafter: "^# Uncomment this to enable the lirc-rpi module"
  notify: Reboot required
  ignore_errors: "{{ ansible_check_mode }}"

- name: Configure config.txt for lirc tx
  ansible.builtin.lineinfile:
    path: "{{ james_on_rpi_config_dir }}/config.txt"
    regexp: "^dtoverlay=gpio-ir-tx,gpio_pin="
    line: "dtoverlay=gpio-ir-tx,gpio_pin={{ james2_gpio_ir_tx_pin }}"
    insertafter: "^dtoverlay=gpio-ir,gpio_pin"
  notify: Reboot required
  ignore_errors: "{{ ansible_check_mode }}"

# install lircd (and workaround some bugs...)
- name: Import tasks from lircd-debian.yml
  ansible.builtin.import_tasks: lircd-debian.yml
  when: ansible_distribution|lower == "debian"

- name: Import tasks from lircd-xbian.yml
  ansible.builtin.import_tasks: lircd-xbian.yml
  when: ansible_distribution|lower == "xbian"
