---

# Depricated, delete when evdev is working

# the lirc package is ultimatively stupid and fails at installaion because the .dist file is not renamed to "non dist" if no other file is available ...
# so, the lirc package can not be installed by ansible without very big fuckery ... sry you had to come here and find this comment ... AGAIN
- name: install required JamesII packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present

# ensure mounted boot
- name: mount boot
  ansible.posix.mount:
    path: /boot
    state: mounted
    src: /dev/mmcblk0p1
    fstype: vfat
  changed_when: false

# configuring RPI GPIO
- name: configure config.txt for lirc rx
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    regexp: '^dtoverlay=gpio-ir,gpio_pin='
    line: "dtoverlay=gpio-ir,gpio_pin={{ james2_lirc_rx_pin }}"
    insertafter: '^# Uncomment this to enable the lirc-rpi module'
  notify: reboot required
  ignore_errors: "{{ ansible_check_mode }}"

- name: configure config.txt for lirc tx
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    regexp: '^dtoverlay=gpio-ir-tx,gpio_pin='
    line: "dtoverlay=gpio-ir-tx,gpio_pin={{ james2_lirc_tx_pin }}"
    insertafter: '^dtoverlay=gpio-ir,gpio_pin'
  notify: reboot required
  ignore_errors: "{{ ansible_check_mode }}"

# install lircd (and workaround some bugs...)
- import_tasks: lircd-buster.yml
  when: ansible_distribution|lower == "debian"

- import_tasks: lircd-xbian.yml
  when: ansible_distribution|lower == "xbian"
