---
- name: Ensure the JamesII user exists
  ansible.builtin.user:
    name: "{{ james_on_rpi_os_user }}"
    system: true
    createhome: true
    home: "/var/lib/{{ james_on_rpi_os_user }}"
    state: present
  become: true
  become_user: root

- name: Gather james_on_rpi_os_user user infos
  ansible.builtin.getent:
    database: passwd
    key: "{{ james_on_rpi_os_user }}"

- name: Lookup home and group for james_on_rpi_os_user
  ansible.builtin.set_fact:
    james_on_rpi_os_user_group: "{{ getent_passwd[james_on_rpi_os_user][2] }}"

# install james2
- name: Import tasks from james2.yml
  ansible.builtin.import_tasks: james2.yml

# install bluetooth (plugin presence)
- name: Import tasks from btpresence.yml
  ansible.builtin.import_tasks: btpresence.yml
  when: "'btpresence' in james_on_rpi_features"

# install caldav (plugin caldav-calendar)
- name: Import tasks from caldav.yml
  ansible.builtin.import_tasks: caldav.yml
  when: "'caldav' in james_on_rpi_features"

# install evdev (plugin evdev-plugin)
- name: Import tasks from evdev.yml
  ansible.builtin.import_tasks: evdev.yml
  when: "'evdev' in james_on_rpi_features"

# install motion (plugin motion)
- name: Import tasks from motion.yml
  ansible.builtin.import_tasks: motion.yml
  when: "'motion' in james_on_rpi_features"

# install mpd (plugin mpd-client)
- name: Import tasks from mpd.yml
  ansible.builtin.import_tasks: mpd.yml
  when: "'mpd' in james_on_rpi_features"

# install raspberry (plugin raspberry)
- name: Import tasks from raspberry.yml
  ansible.builtin.import_tasks: raspberry.yml
  when: "'raspberry' in james_on_rpi_features"

# install rgb-led (plugin rgb-led)
- name: Import tasks from rgb-led.yml
  ansible.builtin.import_tasks: rgb-led.yml
  when: "'rgb-led' in james_on_rpi_features"

# install transmission (plugin transmission)
- name: Import tasks from transmission.yml
  ansible.builtin.import_tasks: transmission.yml
  when: "'transmission' in james_on_rpi_features"

# configure usb_mpc_remote
- name: Import tasks from usb_mpc_remote.yml
  ansible.builtin.import_tasks: usb_mpc_remote.yml
  when:
    - ansible_architecture|lower in james_on_rpi_arm_versions
    - "'usb_mpc_remote' in james_on_rpi_features"
