---
# ensure mounted boot
- name: Mount boot
  ansible.posix.mount:
    path: /boot
    state: mounted
    src: /dev/mmcblk0p1
    fstype: vfat
  changed_when: false

# get user
- name: Looking up users
  ansible.builtin.getent:
    database: passwd

- name: Setting default user to xbian
  ansible.builtin.set_fact:
    james_os_user: xbian
  when: ansible_distribution|lower == "xbian"

- name: Setting default user to pi
  ansible.builtin.set_fact:
    james_os_user: pi
  when: ansible_distribution|lower == "debian"

# Depricated, delete when evdev is working
# also remove the no longer required lirc cfg files under templates
# install lircd (plugin lirc-client)
# - name: Import tasks from lircd.yml
#   ansible.builtin.import_tasks: lircd.yml
#   when: "'lircd' in james2_features"

# - name: Install python requirements virtualenv
#   ansible.builtin.pip:
#     virtualenv_python: python3
#     name:
#       - virtualenv

# install james2
- name: Import tasks from james2.yml
  ansible.builtin.import_tasks: james2.yml

# install evdev (plugin evdev-client)
- name: Import tasks from evdev.yml
  ansible.builtin.import_tasks: evdev.yml
  when: "'evdev' in james2_features"

# install mpd (plugin mpd-client)
- name: Import tasks from mpd.yml
  ansible.builtin.import_tasks: mpd.yml
  when: "'mpd' in james2_features"

# install i2c (plugin rgb-led)
- name: Import tasks from i2c.yml
  ansible.builtin.import_tasks: i2c.yml
  when: "'i2c' in james2_features"

# configure usb_mpc_remote
- name: Import tasks from usb_mpc_remote.yml
  ansible.builtin.import_tasks: usb_mpc_remote.yml
  when: "'usb_mpc_remote' in james2_features"

# install motion (plugin motion)
- name: Import tasks from motion.yml
  ansible.builtin.import_tasks: motion.yml
  when: "'motion' in james2_features"

# install bluetooth (plugin presence)
- name: Import tasks from btpresence.yml
  ansible.builtin.import_tasks: btpresence.yml
  when: "'btpresence' in james2_features"
