---
# get user
- name: Looking up users
  ansible.builtin.getent:
    database: passwd

- name: Ensure the JamesII user exists
  ansible.builtin.user:
    name: "{{ james_on_rpi_os_user }}"
    createhome: true
    state: present
  become: true
  become_user: root

# Depricated, delete when evdev is working
# also remove the no longer required lirc cfg files under templates
# install lircd (plugin lirc-client)
# - name: Import tasks from lircd.yml
#   ansible.builtin.import_tasks: lircd.yml
#   when: "'lircd' in james_on_rpi_features"

# - name: Install python requirements virtualenv
#   ansible.builtin.pip:
#     virtualenv_python: python3
#     name:
#       - virtualenv

# install james2
- name: Import tasks from james2.yml
  ansible.builtin.import_tasks: james2.yml

# install evdev (plugin evdev-client)
- name: Import tasks from evdev.yml
  ansible.builtin.import_tasks: evdev.yml
  when: "'evdev' in james_on_rpi_features"

# install mpd (plugin mpd-client)
- name: Import tasks from mpd.yml
  ansible.builtin.import_tasks: mpd.yml
  when: "'mpd' in james_on_rpi_features"

# install i2c (plugin rgb-led)
- name: Import tasks from i2c.yml
  ansible.builtin.import_tasks: i2c.yml
  when: "'i2c' in james_on_rpi_features"

# configure usb_mpc_remote
- name: Import tasks from usb_mpc_remote.yml
  ansible.builtin.import_tasks: usb_mpc_remote.yml
  when:
    - ansible_architecture|lower in james_on_rpi_arm_versions
    - "'usb_mpc_remote' in james_on_rpi_features"

# install motion (plugin motion)
- name: Import tasks from motion.yml
  ansible.builtin.import_tasks: motion.yml
  when: "'motion' in james_on_rpi_features"

# install bluetooth (plugin presence)
- name: Import tasks from btpresence.yml
  ansible.builtin.import_tasks: btpresence.yml
  when: "'btpresence' in james_on_rpi_features"
