---

- name: Add the Kaliko APT key by package
  ansible.builtin.apt:
    deb: https://deb.kaliko.me/kaliko-archive-keyring.deb

- name: Add Kaliko Repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/deb.kaliko.me.gpg] https://deb.kaliko.me/raspbian-backports/ {{ ansible_distribution_release }}-backports main"
    state: present
    filename: kaliko

- name: Update apt cache for Kaliko repo
  ansible.builtin.apt:
    name: mpd
    default_release: stable-backports
    update_cache: true
    state: present

- name: Install required mpd packages for james2
  ansible.builtin.package:
    name:
      - alsa-utils
      - espeak
      - mpc
    state: present

- name: "Adding existing user to group audio: {{ james_os_user }}"
  ansible.builtin.user:
    name: '{{ james_os_user }}'
    groups: audio
    append: true

# ensure mounted boot
- name: Mount boot
  ansible.posix.mount:
    path: /boot
    state: mounted
    src: /dev/mmcblk0p1
    fstype: vfat
  changed_when: false

- name: Configure config.txt for lirc rx
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    regexp: '^dtparam=audio='
    line: "dtparam=audio=on"
  notify: Reboot required
  ignore_errors: "{{ ansible_check_mode }}"
  when: "'hifiberry' not in group_names"

- name: Configure config.txt for lirc rx
  ansible.builtin.lineinfile:
    path: /etc/mpd.conf
    regexp: '^bind_to_address'
    line: 'bind_to_address		"*"'
    # line: 'bind_to_address		"/run/mpd/socket"'
  notify: Restart mpd
  ignore_errors: "{{ ansible_check_mode }}"

- name: Fix logfile permissions
  ansible.builtin.file:
    path: /var/log/mpd/mpd.log
    owner: mpd
    group: audio
    mode: '0644'

- name: Set volume via amixer
  ansible.builtin.command: amixer set 'PCM' 98%
  changed_when: false
  failed_when: false

- name: Disable and stop mpd socket
  ansible.builtin.service:
    name: mpd.socket
    state: stopped
    enabled: false
  when: ansible_service_mgr == "systemd"

- name: Enable and start mpd service
  ansible.builtin.service:
    name: mpd.service
    state: started
    enabled: true
  when: ansible_service_mgr == "systemd"

- name: Start mpd service
  ansible.builtin.service:
    name: mpd
    state: started
    enabled: true
  when: ansible_service_mgr == "upstart"

- name: Deploy pink noise file
  ansible.builtin.copy:
    src: pink_noise.wav
    dest: /var/lib/mpd/music/pink_noise.wav
    owner: root
    group: root
    mode: '0644'

- name: Install python requirements for mpd
  ansible.builtin.pip:
    name:
      - python-mpd2
    virtualenv: "{{ james2_install_dir }}/venv"
