---
## Backport from kaliko for buster and bullseye

- name: Setup mpd for buster and bullseye with kaliko repo for current mpd
  when: ansible_distribution_release in ['buster','bullseye']
  block:
    - name: Add the Kaliko APT key by package for buster and bullseye
      ansible.builtin.apt:
        deb: https://deb.kaliko.me/kaliko-archive-keyring.deb
      become: true
      become_user: root

    - name: Add Kaliko Repository for buster and bullseye
      ansible.builtin.apt_repository:
        repo: >
          deb [signed-by=/usr/share/keyrings/deb.kaliko.me.gpg]
          https://deb.kaliko.me/raspbian-backports/ {{ ansible_distribution_release }}-backports main
        state: present
        filename: kaliko
      become: true
      become_user: root

    - name: Update apt cache for Kaliko repo in buster and bullseye
      ansible.builtin.apt:
        name: mpd
        default_release: "{{ ansible_distribution_release }}-backports"
        update_cache: true
        state: present
      become: true
      become_user: root

    - name: Fix logfile permissions
      ansible.builtin.file:
        path: /var/log/mpd/mpd.log
        owner: mpd
        group: audio
        mode: "0644"
      become: true
      become_user: root

## "Normal" mpd install starting from bookworm

- name: Setup mpd for bookworm and onwards
  when: ansible_distribution_release not in ['buster','bullseye']
  block:
    - name: Remove remaining kaliko keyring
      ansible.builtin.apt:
        name: kaliko-archive-keyring
        state: absent
      become: true
      become_user: root

    - name: Remove Kaliko Repository when not buster and bullseye
      ansible.builtin.apt_repository:
        repo: >
          deb [signed-by=/usr/share/keyrings/deb.kaliko.me.gpg]
          https://deb.kaliko.me/raspbian-backports/ {{ ansible_distribution_release }}-backports main
        state: absent
        filename: kaliko
      become: true
      become_user: root

    - name: Update apt cache for Kaliko repo in buster and bullseye
      ansible.builtin.apt:
        name: mpd
        update_cache: true
        state: present
      become: true
      become_user: root

- name: Install required mpd packages for james2
  ansible.builtin.package:
    name:
      - alsa-utils
      - espeak-ng
      - mpc
    state: present
  become: true
  become_user: root

- name: "Adding existing user to group audio: {{ james_on_rpi_os_user }}"
  ansible.builtin.user:
    name: "{{ james_on_rpi_os_user }}"
    groups: audio
    append: true
  become: true
  become_user: root

# ensure mounted boot
- name: Override config.txt location for Raspberry Pi OS version before bookworm
  ansible.builtin.set_fact:
    james_on_rpi_config_dir: /boot
  when:
    - ansible_architecture|lower in james_on_rpi_arm_versions
    - ansible_distribution_major_version | int < 12

- name: Override Raspberry PI boot device default since raspberry_pi_boot_dev is set
  ansible.builtin.set_fact:
    james_on_rpi_rpi_boot_dev: "{{ raspberry_pi_boot_dev }}"
  when:
    - ansible_architecture|lower in james_on_rpi_arm_versions
    - raspberry_pi_boot_dev | default('', true) | trim != ''

- name: Mount boot
  ansible.posix.mount:
    path: "{{ james_on_rpi_config_dir }}"
    state: mounted
    src: "{{ james_on_rpi_rpi_boot_dev }}"
    fstype: vfat
  when: ansible_architecture|lower in james_on_rpi_arm_versions
  changed_when: false
  become: true
  become_user: root

- name: Configure config.txt to enable audio
  ansible.builtin.lineinfile:
    path: "{{ james_on_rpi_config_dir }}/config.txt"
    regexp: "^dtparam=audio="
    line: "dtparam=audio=on"
  when:
    - ansible_architecture|lower in james_on_rpi_arm_versions
    - "'hifiberry' not in group_names"
  notify: Reboot required
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root

- name: Configure bind address for mpd # noqa no-tabs
  ansible.builtin.lineinfile:
    path: /etc/mpd.conf
    regexp: "^bind_to_address"
    line: 'bind_to_address		"*"'
    # line: 'bind_to_address		"/run/mpd/socket"'
  notify: Restart mpd
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root

- name: Set volume via amixer
  ansible.builtin.command: amixer set 'PCM' 98%
  changed_when: false
  failed_when: false
  become: true
  become_user: root

- name: Disable and stop mpd socket
  ansible.builtin.service:
    name: mpd.socket
    state: stopped
    enabled: false
  when: ansible_service_mgr == "systemd"
  become: true
  become_user: root

- name: Enable and start mpd service
  ansible.builtin.service:
    name: mpd.service
    state: started
    enabled: true
  when: ansible_service_mgr == "systemd"
  become: true
  become_user: root

- name: Start mpd service
  ansible.builtin.service:
    name: mpd
    state: started
    enabled: true
  when: ansible_service_mgr == "upstart"
  become: true
  become_user: root

- name: Deploy pink noise file
  ansible.builtin.copy:
    src: pink_noise.wav
    dest: /var/lib/mpd/music/pink_noise.wav
    owner: root
    group: root
    mode: "0644"
  become: true
  become_user: root

- name: Install python requirements for mpd
  ansible.builtin.pip:
    name:
      - python-mpd2
    virtualenv: "{{ james_on_rpi_install_dir }}/venv"
  become: true
  become_user: "{{ james_on_rpi_os_user }}"
