---

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslogd
    state: restarted
  ignore_errors: true

- name: Restart lircd
  ansible.builtin.service:
    name: lircd
    state: restarted

- name: Restart lirc
  ansible.builtin.service:
    name: lirc
    state: restarted

- name: Reboot required
  ansible.builtin.reboot:
    reboot_timeout: 300

- name: Restart mpd
  ansible.builtin.service:
    name: mpd
    state: restarted

- name: Restart james2
  ansible.builtin.service:
    name: james2
    state: restarted
